server:
  port: 8765


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: taskService
          uri: http://localhost:8080/
          predicates:
            - Path=/tasks/**